name: VirtualMuseum

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: VirtualMuseum-frontend
    env_file:
      - ./frontend/.env
    ports:
      - "3000:3000"
    restart: unless-stopped
